package com.opencnc.beans;
// Generated 14/05/2014 12:34:47 AM by Hibernate Tools 3.6.0



/**
 * Arco generated by hbm2java
 */
public class Arco  implements java.io.Serializable {


     private int elementoId;
     private ElementoGrafico elementoGrafico;
     private int radio;
     private float angulo1;
     private float angulo2;

    public Arco() {
    }

    public Arco(ElementoGrafico elementoGrafico, int radio, float angulo1, float angulo2) {
       this.elementoGrafico = elementoGrafico;
       this.radio = radio;
       this.angulo1 = angulo1;
       this.angulo2 = angulo2;
    }
   
    public int getElementoId() {
        return this.elementoId;
    }
    
    public void setElementoId(int elementoId) {
        this.elementoId = elementoId;
    }
    public ElementoGrafico getElementoGrafico() {
        return this.elementoGrafico;
    }
    
    public void setElementoGrafico(ElementoGrafico elementoGrafico) {
        this.elementoGrafico = elementoGrafico;
    }
    public int getRadio() {
        return this.radio;
    }
    
    public void setRadio(int radio) {
        this.radio = radio;
    }
    public float getAngulo1() {
        return this.angulo1;
    }
    
    public void setAngulo1(float angulo1) {
        this.angulo1 = angulo1;
    }
    public float getAngulo2() {
        return this.angulo2;
    }
    
    public void setAngulo2(float angulo2) {
        this.angulo2 = angulo2;
    }




}


