package com.opencnc.beans;
// Generated 14/05/2014 12:34:47 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Comando generated by hbm2java
 */
public class Comando  implements java.io.Serializable {


     private int comandoId;
     private TipoCodigo tipoCodigo;
     private String variable;
     private String nombre;
     private String descripcion;
     private Set sentencias = new HashSet(0);

    public Comando() {
    }

	
    public Comando(int comandoId, String variable, String nombre) {
        this.comandoId = comandoId;
        this.variable = variable;
        this.nombre = nombre;
    }
    public Comando(int comandoId, TipoCodigo tipoCodigo, String variable, String nombre, String descripcion, Set sentencias) {
       this.comandoId = comandoId;
       this.tipoCodigo = tipoCodigo;
       this.variable = variable;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.sentencias = sentencias;
    }
   
    public int getComandoId() {
        return this.comandoId;
    }
    
    public void setComandoId(int comandoId) {
        this.comandoId = comandoId;
    }
    public TipoCodigo getTipoCodigo() {
        return this.tipoCodigo;
    }
    
    public void setTipoCodigo(TipoCodigo tipoCodigo) {
        this.tipoCodigo = tipoCodigo;
    }
    public String getVariable() {
        return this.variable;
    }
    
    public void setVariable(String variable) {
        this.variable = variable;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getSentencias() {
        return this.sentencias;
    }
    
    public void setSentencias(Set sentencias) {
        this.sentencias = sentencias;
    }




}


