package com.opencnc.beans;
// Generated 14/05/2014 12:34:47 AM by Hibernate Tools 3.6.0



/**
 * Linea generated by hbm2java
 */
public class Linea  implements java.io.Serializable {


     private int elementoId;
     private ElementoGrafico elementoGrafico;
     private int posicionX2;
     private int posicionY2;

    public Linea() {
    }

    public Linea(ElementoGrafico elementoGrafico, int posicionX2, int posicionY2) {
       this.elementoGrafico = elementoGrafico;
       this.posicionX2 = posicionX2;
       this.posicionY2 = posicionY2;
    }
   
    public int getElementoId() {
        return this.elementoId;
    }
    
    public void setElementoId(int elementoId) {
        this.elementoId = elementoId;
    }
    public ElementoGrafico getElementoGrafico() {
        return this.elementoGrafico;
    }
    
    public void setElementoGrafico(ElementoGrafico elementoGrafico) {
        this.elementoGrafico = elementoGrafico;
    }
    public int getPosicionX2() {
        return this.posicionX2;
    }
    
    public void setPosicionX2(int posicionX2) {
        this.posicionX2 = posicionX2;
    }
    public int getPosicionY2() {
        return this.posicionY2;
    }
    
    public void setPosicionY2(int posicionY2) {
        this.posicionY2 = posicionY2;
    }




}


