package com.opencnc.beans;
// Generated 14/05/2014 12:34:47 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Programa generated by hbm2java
 */
public class Programa  implements java.io.Serializable {


     private Integer programaId;
     private Modelo modelo;
     private String descripcion;
     private Set sentencias = new HashSet(0);

    public Programa() {
    }

	
    public Programa(Modelo modelo, String descripcion) {
        this.modelo = modelo;
        this.descripcion = descripcion;
    }
    public Programa(Modelo modelo, String descripcion, Set sentencias) {
       this.modelo = modelo;
       this.descripcion = descripcion;
       this.sentencias = sentencias;
    }
   
    public Integer getProgramaId() {
        return this.programaId;
    }
    
    public void setProgramaId(Integer programaId) {
        this.programaId = programaId;
    }
    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getSentencias() {
        return this.sentencias;
    }
    
    public void setSentencias(Set sentencias) {
        this.sentencias = sentencias;
    }
    
    public void setModelo(Integer id) {
        
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    




}


