package com.opencnc.beans;
// Generated 14/05/2014 12:34:47 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer rolId;
     private String codigo;
     private String nombreRol;
     private int creadoPor;
     private Date creadoFecha;
     private Integer modificadoPor;
     private Date modificadoFecha;
     private Set usuarios = new HashSet(0);

    public Rol() {
    }

	
    public Rol(String codigo, String nombreRol, int creadoPor, Date creadoFecha) {
        this.codigo = codigo;
        this.nombreRol = nombreRol;
        this.creadoPor = creadoPor;
        this.creadoFecha = creadoFecha;
    }
    public Rol(String codigo, String nombreRol, int creadoPor, Date creadoFecha, Integer modificadoPor, Date modificadoFecha, Set usuarios) {
       this.codigo = codigo;
       this.nombreRol = nombreRol;
       this.creadoPor = creadoPor;
       this.creadoFecha = creadoFecha;
       this.modificadoPor = modificadoPor;
       this.modificadoFecha = modificadoFecha;
       this.usuarios = usuarios;
    }
   
    public Integer getRolId() {
        return this.rolId;
    }
    
    public void setRolId(Integer rolId) {
        this.rolId = rolId;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    public int getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(int creadoPor) {
        this.creadoPor = creadoPor;
    }
    public Date getCreadoFecha() {
        return this.creadoFecha;
    }
    
    public void setCreadoFecha(Date creadoFecha) {
        this.creadoFecha = creadoFecha;
    }
    public Integer getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(Integer modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getModificadoFecha() {
        return this.modificadoFecha;
    }
    
    public void setModificadoFecha(Date modificadoFecha) {
        this.modificadoFecha = modificadoFecha;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


