package com.opencnc.beans;
// Generated 14/05/2014 12:34:47 AM by Hibernate Tools 3.6.0



/**
 * Sentencia generated by hbm2java
 */
public class Sentencia  implements java.io.Serializable {


     private Integer sentenciaId;
     private ElementoGrafico elementoGrafico;
     private Comando comando;
     private Programa programa;
     private int orden;
     private Integer bloque;
     private Float cotaEjeX;
     private Float cotaEjeY;
     private Float cotaEjeZ;
     private Integer velocidadAvance;
     private Integer velocidadHusillo;
     private Integer numeroHerramienta;
     private Integer funcionAuxiliar;
     private String comentario;

    public Sentencia() {
    }

	
    public Sentencia(Comando comando, Programa programa, int orden) {
        this.comando = comando;
        this.programa = programa;
        this.orden = orden;
    }
    public Sentencia(ElementoGrafico elementoGrafico, Comando comando, Programa programa, int orden, Integer bloque, Float cotaEjeX, Float cotaEjeY, Float cotaEjeZ, Integer velocidadAvance, Integer velocidadHusillo, Integer numeroHerramienta, Integer funcionAuxiliar, String comentario) {
       this.elementoGrafico = elementoGrafico;
       this.comando = comando;
       this.programa = programa;
       this.orden = orden;
       this.bloque = bloque;
       this.cotaEjeX = cotaEjeX;
       this.cotaEjeY = cotaEjeY;
       this.cotaEjeZ = cotaEjeZ;
       this.velocidadAvance = velocidadAvance;
       this.velocidadHusillo = velocidadHusillo;
       this.numeroHerramienta = numeroHerramienta;
       this.funcionAuxiliar = funcionAuxiliar;
       this.comentario = comentario;
    }
   
    public Integer getSentenciaId() {
        return this.sentenciaId;
    }
    
    public void setSentenciaId(Integer sentenciaId) {
        this.sentenciaId = sentenciaId;
    }
    public ElementoGrafico getElementoGrafico() {
        return this.elementoGrafico;
    }
    
    public void setElementoGrafico(ElementoGrafico elementoGrafico) {
        this.elementoGrafico = elementoGrafico;
    }
    public Comando getComando() {
        return this.comando;
    }
    
    public void setComando(Comando comando) {
        this.comando = comando;
    }
    public Programa getPrograma() {
        return this.programa;
    }
    
    public void setPrograma(Programa programa) {
        this.programa = programa;
    }
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }
    public Integer getBloque() {
        return this.bloque;
    }
    
    public void setBloque(Integer bloque) {
        this.bloque = bloque;
    }
    public Float getCotaEjeX() {
        return this.cotaEjeX;
    }
    
    public void setCotaEjeX(Float cotaEjeX) {
        this.cotaEjeX = cotaEjeX;
    }
    public Float getCotaEjeY() {
        return this.cotaEjeY;
    }
    
    public void setCotaEjeY(Float cotaEjeY) {
        this.cotaEjeY = cotaEjeY;
    }
    public Float getCotaEjeZ() {
        return this.cotaEjeZ;
    }
    
    public void setCotaEjeZ(Float cotaEjeZ) {
        this.cotaEjeZ = cotaEjeZ;
    }
    public Integer getVelocidadAvance() {
        return this.velocidadAvance;
    }
    
    public void setVelocidadAvance(Integer velocidadAvance) {
        this.velocidadAvance = velocidadAvance;
    }
    public Integer getVelocidadHusillo() {
        return this.velocidadHusillo;
    }
    
    public void setVelocidadHusillo(Integer velocidadHusillo) {
        this.velocidadHusillo = velocidadHusillo;
    }
    public Integer getNumeroHerramienta() {
        return this.numeroHerramienta;
    }
    
    public void setNumeroHerramienta(Integer numeroHerramienta) {
        this.numeroHerramienta = numeroHerramienta;
    }
    public Integer getFuncionAuxiliar() {
        return this.funcionAuxiliar;
    }
    
    public void setFuncionAuxiliar(Integer funcionAuxiliar) {
        this.funcionAuxiliar = funcionAuxiliar;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


