package com.opencnc.beans;
// Generated 14/05/2014 12:34:47 AM by Hibernate Tools 3.6.0



/**
 * Texto generated by hbm2java
 */
public class Texto  implements java.io.Serializable {


     private Integer elementoId;
     private ElementoGrafico elementoGrafico;
     private int tamanio;

    public Texto() {
    }

    public Texto(ElementoGrafico elementoGrafico, int tamanio) {
       this.elementoGrafico = elementoGrafico;
       this.tamanio = tamanio;
    }
   
    public Integer getElementoId() {
        return this.elementoId;
    }
    
    public void setElementoId(Integer elementoId) {
        this.elementoId = elementoId;
    }
    public ElementoGrafico getElementoGrafico() {
        return this.elementoGrafico;
    }
    
    public void setElementoGrafico(ElementoGrafico elementoGrafico) {
        this.elementoGrafico = elementoGrafico;
    }
    public int getTamanio() {
        return this.tamanio;
    }
    
    public void setTamanio(int tamanio) {
        this.tamanio = tamanio;
    }




}


