package com.opencnc.beans;
// Generated 14/05/2014 12:34:47 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TipoCodigo generated by hbm2java
 */
public class TipoCodigo  implements java.io.Serializable {


     private int tipoCodigoId;
     private int nombre;
     private Set comandos = new HashSet(0);

    public TipoCodigo() {
    }

	
    public TipoCodigo(int tipoCodigoId, int nombre) {
        this.tipoCodigoId = tipoCodigoId;
        this.nombre = nombre;
    }
    public TipoCodigo(int tipoCodigoId, int nombre, Set comandos) {
       this.tipoCodigoId = tipoCodigoId;
       this.nombre = nombre;
       this.comandos = comandos;
    }
   
    public int getTipoCodigoId() {
        return this.tipoCodigoId;
    }
    
    public void setTipoCodigoId(int tipoCodigoId) {
        this.tipoCodigoId = tipoCodigoId;
    }
    public int getNombre() {
        return this.nombre;
    }
    
    public void setNombre(int nombre) {
        this.nombre = nombre;
    }
    public Set getComandos() {
        return this.comandos;
    }
    
    public void setComandos(Set comandos) {
        this.comandos = comandos;
    }




}


