package com.opencnc.beans;
// Generated 14/05/2014 12:34:47 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadMedida generated by hbm2java
 */
public class UnidadMedida  implements java.io.Serializable {


     private Integer unidadMedidaId;
     private String nombre;
     private Set modelos = new HashSet(0);

    public UnidadMedida() {
    }

    public UnidadMedida(String nombre, Set modelos) {
       this.nombre = nombre;
       this.modelos = modelos;
    }
   
    public Integer getUnidadMedidaId() {
        return this.unidadMedidaId;
    }
    
    public void setUnidadMedidaId(Integer unidadMedidaId) {
        this.unidadMedidaId = unidadMedidaId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getModelos() {
        return this.modelos;
    }
    
    public void setModelos(Set modelos) {
        this.modelos = modelos;
    }




}


